### PR TITLE
Fixed map refreshing bug

### PR DESCRIPTION
**Pull request by cezaris13**
There was a problem with refreshing ShowIndividualEvent blazor page. I think I fixed it.
 **I would like you to test whether refreshing works for you**, because when I fixed map refreshing problem, there was problem with `StateHasChanged` usage. Thanks.

### CODE REVIEW

**Review by ArentasMeinorius — APPROVED** [review]

**Comment by Mart1nux** [comment]
During testing I created a new event and left the address empty. When opening the show individual event of such event I get an exception.

**Comment by Mart1nux** [comment]
> During testing I created a new event and left the address empty. When opening the show individual event of such event I get an exception.

(Not sure if this is the best place to report this as the refresh worked perfectly fine for me, just decided to extended testing)

**Comment by Mart1nux** [comment]
Another slightly unrelated find - if the address is comprised of numbers an exception is returned.

**Comment by cezaris13** [comment]
> During testing I created a new event and left the address empty. When opening the show individual event of such event I get an exception.

this is fixed now

**Comment by cezaris13** [comment]
> Another slightly unrelated find - if the address is comprised of numbers an exception is returned.

I don't know what number was passed, but with 123456 I get valid address

**Pull request merged**
